# Generated by Django 5.2.4 on 2025-08-01 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_student_grade_remove_teacher_subject_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='bigraphy',
            new_name='biography',
        ),
    ]
