# Generated by Django 5.2.4 on 2025-08-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_bigraphy_teacher_biography'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='biography',
        ),
        migrations.AddField(
            model_name='user',
            name='biography',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
