# Generated by Django 5.2.4 on 2025-08-01 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_teacher_biography_user_biography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='rate',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
